name: 'Deploy Dev'

on:
  push:
    tags:
      - v**beta**

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker core meta
        id: core-meta
        uses: docker/metadata-action@v5
        with:
          images: harbor.ncuos.com/genius-auth/core

      - name: Build Docker Core Image and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile.core
          tags: ${{ steps.core-meta.outputs.tags }}
          labels: ${{ steps.core-meta.outputs.labels }}

      - name: Docker ssh server meta
        id: ssh-server-meta
        uses: docker/metadata-action@v5
        with:
          images: harbor.ncuos.com/genius-auth/ssh-server

      - name: Build Docker SSH Server Image and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./Dockerfile.ssh
          tags: ${{ steps.ssh-server-meta.outputs.tags }}
          labels: ${{ steps.ssh-server-meta.outputs.labels }}

      - name: Update Deployments
        uses: MultiMx/K8sQuickUpdateAction@v0.7
        with:
          k8s: |
            dev:
              backend: https://rancher.ncuhome.club
              token: ${{ secrets.CATTLE_TOKEN_LOCAL }}
          workloads: |
            -
              genius-auth:
                core:
                  image: ${{ steps.image.outputs.CORE_VERSION }}
                  wait: true
            -
              genius-auth:
                ssh-server:
                  image: ${{ steps.image.outputs.SSH_DEV_VERSION }}